name: IPTV自动抓取更新

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

# 解决Node20弃用警告 + 授权写入仓库
permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 配置Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 安装依赖
        run: pip install -r requirements.txt

      - name: 运行抓取脚本
        run: python main.py

      # 关键：配置git用户，不然无法提交
      - name: 设置Git提交身份
        run: |
          git config user.name "IPTV Bot"
          git config user.email "bot@github.com"

      - name: 提交并推送生成文件
        run: |
          git add live.txt live.m3u
          git commit -m "Auto update iptv source"
          git push
